#!/bin/bash
# Get Firebase Config for FCM

echo "========================================="
echo "Firebase Config Needed for FCM"
echo "========================================="
echo ""
echo "Go to Firebase Console:"
echo "1. https://console.firebase.google.com/project/frizzly-9a65f/settings/general"
echo "2. Scroll to 'Your apps' section"
echo "3. Click on Web app (</> icon)"
echo "4. Copy these values:"
echo ""
echo "   - apiKey"
echo "   - messagingSenderId"
echo "   - appId"
echo ""
echo "5. Go to Cloud Messaging tab:"
echo "   https://console.firebase.google.com/project/frizzly-9a65f/settings/cloudmessaging"
echo "6. Under 'Web Push certificates', click 'Generate key pair'"
echo "7. Copy the VAPID key"
echo ""
echo "Then update the files I'll create with these values."
echo ""
